### ISSUE TITLE
taq create indexer gets ' Config does not contain sandbox 'local' ' error

### ISSUE THREAD

**Issue by michaelkernaghan** [ecadlabs/taqueria-scaffold-taco-shop#39]
1.  taq scaffold https://github.com/ecadlabs/taqueria-scaffold-taco-shop
2.  cd  taqueria-taco-shop
3. taq install @tezos-dappetizer/taqueria
4. taq start sandbox && taq deploy hello-tacos.tz
5. do funding if needed, and redo 4 after funding
6. taq create indexer get error (below)
7. note also error has a grammar mistake " which is a fallback if options '--sandbox' nor '--network' are specified." should be " which is a fallback if neither options '--sandbox' nor '--network' are specified."
8. note as well both ' taq create indexer --network' and ' taq create indexer --scaffold' get the same error
```
Error: Config does not contain sandbox 'local' which is a fallback if options '--sandbox' nor '--network' are specified.
    at resolve (/home/michael/taqueria-taco-shop/node_modules/@tezos-dappetizer/taqueria/dist/bundle.commonjs.js:245:15)
    at TezosNodeResolver.resolve (/home/michael/taqueria-taco-shop/node_modules/@tezos-dappetizer/taqueria/dist/bundle.commonjs.js:234:16)
    at TaqueriaRunner.initDappetizerCommand (/home/michael/taqueria-taco-shop/node_modules/@tezos-dappetizer/taqueria/dist/bundle.commonjs.js:276:53)
    at TaqueriaRunner.run (/home/michael/taqueria-taco-shop/node_modules/@tezos-dappetizer/taqueria/dist/bundle.commonjs.js:266:29)
    at async runDappetizerTaqueria (/home/michael/taqueria-taco-shop/node_modules/@tezos-dappetizer/taqueria/dist/bundle.commonjs.js:391:5)
    at async handler (/home/michael/taqueria-taco-shop/node_modules/@tezos-dappetizer/taqueria/dist/bundle.commonjs.js:382:17)
```

**Comment by hu3man** [comment]
@michaelkernaghan , please refile this as a bug ticket
