### ISSUE TITLE
[Bug]: Getting strange output when i try to compile

### ISSUE THREAD

**Issue by tulpenhaendler** [ecadlabs/taqueria-scaffold-taco-shop#5]
When i follow the Readme up to `taq compile` I get a strange output:

```
parallels@ubuntu-linux-20-04-desktop:~/Projects$ taq scaffold https://github.com/ecadlabs/taqueria-scaffold-taco-shop taco-shop                                                

 Scaffolding 🛠 
 into: /home/parallels/Projects/taco-shop
 from: https://github.com/ecadlabs/taqueria-scaffold-taco-shop 

Cloning into '/home/parallels/Projects/taco-shop'...


 Initializing Project...
    ✓ Remove Git directory
    ✓ Install plugins
    ✓ Run scaffold post-init script
    ✓ Project Taq'ified 

🌮 Project created successfully 🌮
parallels@ubuntu-linux-20-04-desktop:~/Projects$ 
parallels@ubuntu-linux-20-04-desktop:~/Projects$ 
parallels@ubuntu-linux-20-04-desktop:~/Projects$ 
parallels@ubuntu-linux-20-04-desktop:~/Projects$ 
parallels@ubuntu-linux-20-04-desktop:~/Projects$ cd taco-shop/
parallels@ubuntu-linux-20-04-desktop:~/Projects/taco-shop$ ls
app  artifacts  contracts  LICENSE  node_modules  package.json  package-lock.json  README.md  scaffold.log  tests
parallels@ubuntu-linux-20-04-desktop:~/Projects/taco-shop$ taq init
Project taq'ified!
parallels@ubuntu-linux-20-04-desktop:~/Projects/taco-shop$ npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm64"})

audited 425 packages in 1.117s
found 0 vulnerabilities

parallels@ubuntu-linux-20-04-desktop:~/Projects/taco-shop$ 
parallels@ubuntu-linux-20-04-desktop:~/Projects/taco-shop$ taq compile
/home/parallels/Projects/taco-shop/node_modules/@taqueria/plugin-ligo/index.js:16
        const projectDir = process.env.PROJECT_DIR ?? opts.projectDir;
                                                    ^

SyntaxError: Unexpected token '?'
    at Module._compile (internal/modules/cjs/loader.js:892:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11
/home/parallels/Projects/taco-shop/node_modules/@taqueria/plugin-jest/index.js:2
import { Option, Plugin, PositionalArg, Task, Template } from "@taqueria/node-sdk";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Module._compile (internal/modules/cjs/loader.js:892:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11
/home/parallels/Projects/taco-shop/node_modules/@taqueria/plugin-flextesa/index.js:59
    const projectDir = process.env.PROJECT_DIR ?? opts.config.projectDir;
                                                ^

SyntaxError: Unexpected token '?'
    at Module._compile (internal/modules/cjs/loader.js:892:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11
/home/parallels/Projects/taco-shop/node_modules/@taqueria/node-sdk/index.js:28074
  const internalSchema27 = params.internalSchema ?? params.rawSchema;
                                                  ^

SyntaxError: Unexpected token '?'
    at Module._compile (internal/modules/cjs/loader.js:892:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/parallels/Projects/taco-shop/node_modules/@taqueria/plugin-taquito/index.js:1:30)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
taq [command]

Commands:
  taq init [projectDir]                     Initialize a new project
  taq opt-in                                Opt-in to sharing anonymous usage an
                                            alytics
  taq opt-out                               Opt-out of sharing anonymous usage a
                                            nalytics
  taq scaffold [scaffoldUrl] [scaffoldProj  Generate a new project using pre-mad
  ectDir]                                   e scaffold

Options:
      --version     Show version number                                [boolean]
      --build       Display build information about the current version[boolean]
  -p, --projectDir  Path to your project directory               [default: "./"]
  -e, --env         Specify an environment configuration

Taqueria is currently in BETA. You've been warned. :)

The @taqueria/plugin-ligo plugin experienced an error when getting information about the @taqueria/plugin-ligo plugin.
parallels@ubuntu-linux-20-04-desktop:~/Projects/taco-shop$ 
```

the steps:
$ taq scaffold
$ tag init
$ npm install
$ taq compile

are what i could figure is the way to do this according to the docs and Readme
but it doesnt work and i cant make sense of the error messages.

**Comment by russellmorton** [comment]
Tracked in: https://github.com/ecadlabs/taqueria/issues/1111

**Comment by sinapsist** [comment]
Linux on ARM/M1 is not supported yet.
